pipeline {
    agent any

    environment {
        JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'git@github.com:it2021035/HuaDoc.git'
            }
        }
        stage('Preparation') {
            steps {
                dir('localDocWebApp') {
                    sh 'chmod +x ./mvnw'
                }
            }
        }
        stage('Test') {
            steps {
                dir('localDocWebApp') {
                    sh './mvnw test'
                }
            }
        }
        stage('Run Ansible Pipeline') {
            steps {
                build job: 'ansible'
            }
        }
        stage('Install Postgres') {
            steps {
                sh '''
                    export ANSIBLE_CONFIG=~/workspace/ansible/ansible-playground/ansible.cfg
                    ansible-playbook -i ~/workspace/ansible/ansible-playground/hosts.yaml -l azure-db-server ~/workspace/ansible/ansible-playground/playbooks/postgres.yaml
                '''
            }
        }
        stage('Deploy Spring Boot App') {
            steps {
                sh '''
                    export ANSIBLE_CONFIG=~/workspace/ansible/ansible.cfg
                    ansible-playbook -i ~/workspace/ansible/ansible-playground/hosts.yaml -l appserver ~/workspace/ansible/ansible-playground/playbooks/spring.yaml
                '''
            }
        }
        stage('Deploy Frontend') {
            steps {
                sh '''
                    export ANSIBLE_CONFIG=~/workspace/ansible/ansible-playground/ansible.cfg
                    ansible-playbook -i ~/workspace/ansible/ansible-playground/hosts.yaml -l frontserver ~/workspace/ansible/ansible-playground/playbooks/vue.yaml
                '''
            }
        }
    }
}